name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo ./build.sh
    - run: find .
    - uses: actions/upload-artifact@v2
      with:
        name: my-raspi-image
        path: ubuntu-18.04-raspberrypi-arm64.img
