name: Build Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu-20.04-raspberrypi-arm64
        path: ubuntu-20.04-raspberrypi-arm64.img
